//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class admin
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "This field is Required")]
        public string username { get; set; }

        [Required(ErrorMessage = "This field is Required")]
        public string password { get; set; }
       
    }
}
